### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by ramonakira**

### CODE REVIEW

**Comment by jaap3** [comment]
I don't think this is necessary, it is documented (in detail) in the [prettier docs](https://prettier.io/docs/en/ignore.html)

**Comment by ramonakira** [comment]
Maybe then a link to the prettier docs, but a set list of file(types) that we want to always ignore would be helpful I think.

**Comment by ramonakira** [comment]
Alright, I changed it to be just a sentence.

**Comment by twesterhuis** [comment]
I agree that we shouldn't try to push ignores we're using in some projects that may not make sense in other projects. What I'd like is that for each project it is determined what is needed and what is not. 

The `.yml` and `.md` ignores should also probably be temporary as we do that mainly for consistency now.

The link to the Prettier docs is nice.

**Review by twesterhuis — APPROVED** [review]

**Pull request merged**
